[theme]
base = "light"
backgroundColor = "#f9f9f7"
secondaryBackgroundColor = "#fcfcfb"
textColor = "#0b0b0b"
primaryColor = "#2a78d6"

[theme.sidebar]
backgroundColor = "#141e33"
secondaryBackgroundColor = "#1f2b45"
textColor = "#f5f5f4"
primaryColor = "#FFD700"
